export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_PLAYING = 'SET_PLAYING';
export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY';
export const SET_PLAY_FULL = 'SET_PLAY_FULL';
export const SET_PLAY_MODE = 'SET_PLAY_MODE';
export const SET_PLAY_INDEX = 'SET_PLAY_INDEX';

export const SET_MUSICLIST = 'SET_MUSICLIST';
export const SET_MUSICLIST_ID = 'SET_MUSICLIST_ID';
export const SET_MUSICLIST_BG = 'SET_MUSICLIST_BG';
export const SET_MUSICLIST_TITLE = 'SET_MUSICLIST_TITLE';

export const SET_SLICE_IMG_LOADED = 'SET_SLICE_IMG_LOADED'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY';

export const SET_LIKED_MUSIC = 'SET_LIKED_MUSIC';